### ISSUE TITLE
cdxResult referenced before assignment

### ISSUE THREAD

**Issue by mikael-s** [bitdruid/python-wayback-machine-downloader#15]
Hello!

When launching `waybackup` I get an exception `local variable 'cdxResult' referenced before assignment`.

**Command to reproduce**

`waybackup -u http://example.com -c`

**Terminal output**
```
-------------------------
!-- Exception: UNCAUGHT EXCEPTION
!-- File: miniforge3/lib/python3.10/site-packages/pywaybackup/archive.py
!-- Function: query_list
!-- Line: 151
!-- Segment: if not cdxResult:
!-- Description: local variable 'cdxResult' referenced before assignment
-------------------------
Exception log: /home/dir/waybackup_snapshots/waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "miniforge3/bin/waybackup", line 8, in <module>
    sys.exit(main())
  File "miniforge3/lib/python3.10/site-packages/pywaybackup/main.py", line 49, in main
    archive.query_list(args.url, args.range, args.start, args.end, args.explicit, mode, args.cdxbackup, args.cdxinject)
  File "miniforge3/lib/python3.10/site-packages/pywaybackup/archive.py", line 151, in query_list
    if not cdxResult:
UnboundLocalError: local variable 'cdxResult' referenced before assignment
```

**Additional context**
I'm using v.1.3.0.

Thanks a lot for your help!

**Comment by bitdruid** [comment]
thx, fixed that
