### ISSUE TITLE
[BUG] database is locked - when writing to external storage

### ISSUE THREAD

**Issue by Tiptop4792** [bitdruid/python-wayback-machine-downloader#26]
Hey! Thanks for the previous fix! Sorry to bother again ...

The previous fix works when files are written to local storage. 

I just wanted to start a larger download and save it to an external storage via the -o operator. It worked with previous versions, however now, it reads:

-------------------------
!-- Exception: UNCAUGHT EXCEPTION
!-- File: waybackdownloaderEnvironment/lib/python3.10/site-packages/pywaybackup/db.py
!-- Function: init
!-- Line: 39
!-- Segment: db.cursor.execute(cls.waybackup_table)
!-- Description: database is locked
-------------------------

I'm on waybackup 2.0.3 running Ubuntu 22.04 and Python 3.10.12

Any idea what's causing this? 

Many thanks!

**Comment by Tiptop4792** [comment]
Some more info from the error log

-------------------------
Version: 2.0.3
-------------------------
Command: -u example.com -f --start 20130101 --end 20181231 -o /home/xyz/Documents/data/wayback-site/ --retry 1 --workers 6 --keep --progress
-------------------------

2024-11-12 14:01:44
-------------------------
!-- Exception: UNCAUGHT EXCEPTION
!-- File: waybackdownloaderEnvironment/lib/python3.10/site-packages/pywaybackup/db.py
!-- Function: init
!-- Line: 39
!-- Segment: db.cursor.execute(cls.waybackup_table)
!-- Description: database is locked
-------------------------
!-- Local Variables:
    -- cls = <class 'pywaybackup.db.Database'>
    -- dbfile = ../../Documents/data/wayback-uefa/uefa-2013-2018/waybackup_uefa.com.db
    -- query_identifier = uefa.com{'current': False, 'full': True, 'save': False}{'explicit': False, 'range': None, 'start': 20130101, 'end': 20181231, 'filetype': None, 'limit': None}
    -- db = <pywaybackup.db.Database object at 0x79f6da163520>
-------------------------
Traceback (most recent call last):
  File "waybackdownloaderEnvironment/bin/waybackup", line 8, in <module>
    sys.exit(main())
  File "waybackdownloaderEnvironment/lib/python3.10/site-packages/pywaybackup/main.py", line 19, in main
    db.init(config.dbfile, config.query_identifier)
  File "waybackdownloaderEnvironment/lib/python3.10/site-packages/pywaybackup/db.py", line 39, in init
    db.cursor.execute(cls.waybackup_table)
sqlite3.OperationalError: database is locked

**Comment by bitdruid** [comment]
your external storage is a hdd / pendrive ? with a regular mountpoint for example like `mount /dev/sda /mnt/storage` ? just asking so i can reproduce :)

**Comment by bitdruid** [comment]
did some tests now. do you install the tool via virtual-env or `--break-system-packages`? tried it with a mounted usb-storage and was not able to set up the database as standard user. but sudo did it.

if you want to use the tool via sudo you have to `source` into your virtual-env with sudo or otherwise do a `pip install` as root.

did the database exist before you started the tool (again)? if so, maybe there is a problem with remaining LOCKS after keyboard-interrupt or something similar...

**Comment by bitdruid** [comment]
in addition please briefly describe your connected cloud storage. what kind? mountpoint? permissions? (`ls -la`) was it a new run without an already existing db?

**Comment by Ghost-chu** [comment]
I also encountered into same issue in pure ubuntu docker container, which mount to local file system.

**Comment by bitdruid** [comment]
thank you for refering that issue again. please give me some time because i'm currently covered with another project for the next 2 month :)

**Comment by bitdruid** [comment]
> I also encountered into same issue in pure ubuntu docker container, which mount to local file system.

did you have a look at this? today i tried it to reproduce with fat16 images / pendrive and was not able to. had no time for docker.. but would be a cool feature to have a docker-container.. maybe with webui🤔

**Comment by bitdruid** [comment]
i will close this for now. if the issue may come up again please reopen and provide details about the setup/permissions/installation :)
