### ISSUE TITLE
hellow你好，我遇到一个问题

### ISSUE THREAD

**Issue by lostmagicblue** [bitdruid/python-wayback-machine-downloader#3]
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/pywaybackup/archive.py", line 165, in download_loop
download_status = download(output, snapshot, connection, status, no_redirect)
File "/usr/local/lib/python3.8/site-packages/pywaybackup/archive.py", line 219, in download
with open(download_file, 'wb') as file:
IsADirectoryError: [Errno 21] Is a directory: '/root/waybackup_snapshots/bbs.eastsea.com.cn/static/image/common'

thank you

**Comment by bitdruid** [comment]
fixed with 1.0.3
